ktlint:
  active: true
  code_style: 'intellij_idea'
  autoCorrect: true
  AnnotationOnSeparateLine:
    active: true
    autoCorrect: true
    indentSize: 4
  AnnotationSpacing:
    active: true
    autoCorrect: true
  ArgumentListWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
    ignoreRuleParameterThreshold: 8
  BackingPropertyNaming:
    active: true
  BinaryExpressionWrapping:
    active: true
    autoCorrect: true
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
    indentSize: 4
  BlankLineBeforeDeclaration:
    active: false
    autoCorrect: true
  BlankLineBetweenWhenConditions:
    active: true
    autoCorrect: true
    lineBreakAfterWhenEntries: true
  BlockCommentInitialStarAlignment:
    active: true
    autoCorrect: true
  ChainMethodContinuation:
    active: false
    autoCorrect: true
    indentSize: 4
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
    forceMultilineWhenChainOperatorCountGreaterOrEqualThan: 4
  ChainWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
  ClassName:
    active: false
  ClassSignature:
    active: true
    autoCorrect: true
    indentSize: 4
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
  CommentSpacing:
    active: true
    autoCorrect: true
  CommentWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
  ConditionWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
  ContextReceiverListWrapping:
    active: true
    autoCorrect: true
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
    indentSize: 4
  ContextReceiverMapping:
    active: true
    autoCorrect: true
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
    indentSize: 4
  EnumEntryNameCase:
    active: true
    aliases: ['EnumEntryName']
    autoCorrect: true
    enumEntryNameCasing: 'upper_or_camel_cases'
  EnumWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
  ExpressionOperandWrapping:
    active: false
    autoCorrect: true
    indentSize: 4
  Filename:
    active: true
  FinalNewline:
    active: true
    autoCorrect: true
    insertFinalNewLine: true
  FunKeywordSpacing:
    active: true
    autoCorrect: true
  FunctionExpressionBody:
    active: true
    autoCorrect: true
    indentSize: 4
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
  FunctionLiteral:
    active: true
    autoCorrect: true
    indentSize: 4
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
  FunctionName:
    active: false
  FunctionReturnTypeSpacing:
    active: true
    autoCorrect: true
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
  FunctionSignature:
    active: true
    autoCorrect: true
    forceMultilineWhenParameterCountGreaterOrEqualThan: 2147483647
    functionBodyExpressionWrapping: 'default'
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
    indentSize: 4
  FunctionStartOfBodySpacing:
    active: true
    autoCorrect: true
  FunctionTypeModifierSpacing:
    active: true
    autoCorrect: true
  FunctionTypeReferenceSpacing:
    active: true
    autoCorrect: true
  IfElseBracing:
    active: false
    autoCorrect: true
    indentSize: 4
  IfElseWrapping:
    active: false
    autoCorrect: true
    indentSize: 4
  ImportOrdering:
    active: true
    autoCorrect: true
    # layout: If the 'code_style' ruleset property is set to 'android', the default is '*', otherwise '*,java.**,javax.**,kotlin.**,^'.
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 4
    indentWhenArrowOnNewLine: false
  Kdoc:
    active: true
  KdocWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
  MaximumLineLength:
    active: true
    aliases: ['MaxLineLength']
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
    ignoreBackTickedIdentifier: false
  MixedConditionOperators:
    active: true
  ModifierListSpacing:
    active: true
    autoCorrect: true
    indentSize: 4
  ModifierOrdering:
    active: true
    autoCorrect: true
  MultiLineIfElse:
    active: true
    autoCorrect: true
    indentSize: 4
  MultilineExpressionWrapping:
    active: false
    autoCorrect: true
    indentSize: 4
    functionBodyExpressionWrapping: 'multiline'
  MultilineLoop:
    active: true
    autoCorrect: true
    indentSize: 4
  NoBlankLineBeforeRbrace:
    active: true
    autoCorrect: true
  NoBlankLineInList:
    active: false
    autoCorrect: true
  NoBlankLinesInChainedMethodCalls:
    active: true
    autoCorrect: true
  NoConsecutiveBlankLines:
    active: true
    autoCorrect: true
  NoConsecutiveComments:
    active: false
  NoEmptyClassBody:
    active: true
    autoCorrect: true
  NoEmptyFile:
    active: true
  NoEmptyFirstLineInClassBody:
    active: false
    autoCorrect: true
    indentSize: 4
  NoEmptyFirstLineInMethodBlock:
    active: true
    autoCorrect: true
  NoLineBreakAfterElse:
    active: true
    autoCorrect: true
  NoLineBreakBeforeAssignment:
    active: true
    autoCorrect: true
  NoMultipleSpaces:
    active: true
    autoCorrect: true
  NoSemicolons:
    active: true
    autoCorrect: true
  NoSingleLineBlockComment:
    active: false
    autoCorrect: true
    indentSize: 4
  NoTrailingSpaces:
    active: true
    autoCorrect: true
  NoUnitReturn:
    active: true
    autoCorrect: true
  NoUnusedImports:
    active: true
    autoCorrect: true
  NoWildcardImports:
    active: true
    packagesToUseImportOnDemandProperty: 'java.util.*,kotlinx.android.synthetic.**'
  NullableTypeSpacing:
    active: true
    autoCorrect: true
  PackageName:
    active: true
  ParameterListSpacing:
    active: true
    autoCorrect: true
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
  ParameterListWrapping:
    active: true
    autoCorrect: true
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
    indentSize: 4
  ParameterWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
  PropertyName:
    active: true
    constantNamingStyle: 'screaming_snake_case'
  PropertyWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
  SpacingAroundAngleBrackets:
    active: true
    autoCorrect: true
  SpacingAroundColon:
    active: true
    autoCorrect: true
  SpacingAroundComma:
    active: true
    autoCorrect: true
  SpacingAroundCurly:
    active: true
    autoCorrect: true
    indentSize: 4
  SpacingAroundDot:
    active: true
    autoCorrect: true
  SpacingAroundDoubleColon:
    active: true
    autoCorrect: true
  SpacingAroundKeyword:
    active: true
    autoCorrect: true
  SpacingAroundOperators:
    active: true
    autoCorrect: true
  SpacingAroundParens:
    active: true
    autoCorrect: true
  SpacingAroundRangeOperator:
    active: true
    autoCorrect: true
  SpacingAroundSquareBrackets:
    active: true
    autoCorrect: true
  SpacingAroundUnaryOperator:
    active: true
    autoCorrect: true
  SpacingBetweenDeclarationsWithAnnotations:
    active: true
    autoCorrect: true
  SpacingBetweenDeclarationsWithComments:
    active: true
    autoCorrect: true
  SpacingBetweenFunctionNameAndOpeningParenthesis:
    active: true
    autoCorrect: true
  StatementWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
  StringTemplate:
    active: true
    autoCorrect: true
  StringTemplateIndent:
    active: false
    autoCorrect: true
    indentSize: 4
  ThenSpacing:
    active: true
    autoCorrect: true
  TrailingCommaOnCallSite:
    active: true
    autoCorrect: true
    # useTrailingCommaOnCallSite: If the 'code_style' ruleset property is set to 'android', the default is 'false', otherwise 'true'.
  TrailingCommaOnDeclarationSite:
    active: true
    autoCorrect: true
    # useTrailingCommaOnDeclarationSite: If the 'code_style' ruleset property is set to 'android', the default is 'false', otherwise 'true'.
  TryCatchFinallySpacing:
    active: false
    autoCorrect: true
    indentSize: 4
  TypeArgumentComment:
    active: true
  TypeArgumentListSpacing:
    active: true
    autoCorrect: true
    indentSize: 4
  TypeParameterComment:
    active: true
  TypeParameterListSpacing:
    active: true
    autoCorrect: true
    indentSize: 4
  UnnecessaryParenthesesBeforeTrailingLambda:
    active: true
    autoCorrect: true
  ValueArgumentComment:
    active: true
  ValueParameterComment:
    active: true
  WhenEntryBracing:
    active: false
    autoCorrect: true
    indentSize: 4
  Wrapping:
    active: true
    autoCorrect: true
    indentSize: 4
    # maxLineLength: If the 'code_style' ruleset property is set to 'android', the default is '100', otherwise '120'.
