language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk12
install: true
script:
  - ./gradlew build --build-cache -PwarningsAsErrors=true
  - ./gradlew shadowJar
  - java -jar ./detekt-cli/build/libs/detekt-cli-*-all.jar --help
  - java -jar ./detekt-cli/build/libs/detekt-cli-*-all.jar -i . --baseline ./reports/baseline.xml -f ".*/resources/.*,.*/build/.*" -c ./detekt-cli/src/main/resources/default-detekt-config.yml,./reports/failfast.yml
  - ./gradlew verifyGeneratorOutput
after_success:
  - .buildscript/deploy_snapshot.sh
  - ./gradlew rootJacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
