language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
script:
  - ./detekt-gradle-plugin/gradlew build
  - ./gradlew build -PwarningsAsErrors=true
  - ./gradlew shadowJar
  - java -jar ./detekt-cli/build/libs/detekt-cli-*-all.jar --help
  - java -jar ./detekt-cli/build/libs/detekt-cli-*-all.jar -i . --baseline ./reports/baseline.xml -f ".*/resources/.*,.*/build/.*" -c ./detekt-cli/src/main/resources/default-detekt-config.yml,./reports/failfast.yml
  - ./gradlew verifyGeneratorOutput
after_success:
  - .buildscript/deploy_snapshot.sh
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
