complexity:
  TooManyFunctions:
    excludes: ["**/test/**", "**/functionalTest/**"]

libraries:
  ForbiddenPublicDataClass:
    active: false
  LibraryEntitiesShouldNotBePublic:
    active: false
  LibraryCodeMustSpecifyReturnType:
    active: true
    excludes: ['**/*.kt']
    includes: ['**/detekt-api/src/main/**/api/*.kt']

naming:
  ClassNaming:
    ignoreAnnotated: ['org.junit.jupiter.api.Nested']
  FunctionNaming:
    active: true
    excludes: []
    ignoreAnnotated: ['Test', 'ParameterizedTest', 'RepeatedTest', 'TestFactory']

performance:
  SpreadOperator:
    excludes: ["**/test/**", "**/functionalTest/**"]

style:
  MagicNumber:
    active: true
    excludes: ["**/test/**", "**/*Test.kt", "**/*Spec.kt"]
  MaxLineLength:
    active: true
    excludes: ["**/test/**", "**/*Test.kt", "**/*Spec.kt"]
    excludeCommentStatements: true

formatting:
  active: true
  MaximumLineLength:
    active: false

potential-bugs:
  DoubleMutabilityForCollection:
    active: true
    mutableTypes:
      - 'kotlin.collections.MutableList'
      - 'kotlin.collections.MutableMap'
      - 'kotlin.collections.MutableSet'
      - 'java.util.ArrayList'
      - 'java.util.LinkedHashSet'
      - 'java.util.HashSet'
      - 'java.util.LinkedHashMap'
      - 'java.util.HashMap'
      - 'org.gradle.api.file.ConfigurableFileCollection'
